### ISSUE TITLE
关于Thread Performance Checker

### ISSUE THREAD

**Issue by ounione** [dgynfi/DYFCodeScanner#1]
您好，可否解决一下这个：
Thread Performance Checker: -[AVCaptureSession startRunning] should be called from background thread. Calling it on the main thread can lead to UI unresponsiveness
PID: 90430, TID: 12678144
Backtrace
=================================================================
3   bluetoothPro                        0x000000010034deec -[DYFCodeScannerViewController configureScanner] + 1976
4   bluetoothPro                        0x000000010034d46c __45-[DYFCodeScannerViewController requestAccess]_block_invoke_2 + 60
5   libdispatch.dylib                   0x0000000103104520 _dispatch_call_block_and_release + 32
6   libdispatch.dylib                   0x0000000103106038 _dispatch_client_callout + 20
7   libdispatch.dylib                   0x0000000103116798 _dispatch_main_queue_drain + 1196
8   libdispatch.dylib                   0x00000001031162dc _dispatch_main_queue_callback_4CF + 44
9   CoreFoundation                      0x0000000192b57c28 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 625704
10  CoreFoundation                      0x0000000192b39560 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 501088
11  CoreFoundation                      0x0000000192b3e3ec CFRunLoopRunSpecific + 612
12  GraphicsServices                    0x00000001ce00335c GSEventRunModal + 164
13  UIKitCore                           0x0000000194ecb6e8 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 3790568
14  UIKitCore                           0x0000000194ecb34c UIApplicationMain + 340
15  bluetoothPro                        0x0000000100278c20 main + 124
16  dyld                                0x00000001b203edec 8A423F3F-B318-315E-99C7-05EE532E9C0D + 89580

**Comment by itenfay** [comment]
闪退了吗？尽快进行修复。

**Comment by ounione** [comment]
> 闪退了吗？尽快进行修复。

请问修复结果如何了

**Comment by itenfay** [comment]
@ounione 已发布新版
